services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.backend
    ports:
      - "8000:8000"
    command: uv run litestar --app=backend.src.app:app run --host 0.0.0.0

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile.frontend
    ports:
      - "8080:8080"
    environment:
      BACKEND_URL: http://backend:8000
    depends_on:
      - backend
