"""initial migration

Revision ID: 1026a1e7228f
Revises: 
Create Date: 2025-11-29 18:20:33.343238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from advanced_alchemy.types.guid import GUID


# revision identifiers, used by Alembic.
revision: str = '1026a1e7228f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('move',
    sa.Column('id', GUID(length=16), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_move')),
    sa.UniqueConstraint('machine_id', name=op.f('uq_move_machine_id')),
    sa.UniqueConstraint('name', name=op.f('uq_move_name'))
    )
    op.create_table('pokemon',
    sa.Column('id', GUID(length=16), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('sprite_url', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('genus', sa.String(), nullable=False),
    sa.Column('types_display', sa.String(), nullable=False),
    sa.Column('is_legendary', sa.Boolean(), nullable=False),
    sa.Column('is_mythical', sa.Boolean(), nullable=False),
    sa.Column('is_ultra_beast', sa.Boolean(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pokemon')),
    sa.UniqueConstraint('name', name=op.f('uq_pokemon_name')),
    sa.UniqueConstraint('number', name=op.f('uq_pokemon_number')),
    sa.UniqueConstraint('sprite_url', name=op.f('uq_pokemon_sprite_url'))
    )
    op.create_table('type',
    sa.Column('id', GUID(length=16), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_type')),
    sa.UniqueConstraint('name', name=op.f('uq_type_name'))
    )
    op.create_table('pokemon_move',
    sa.Column('pokemon_id', sa.UUID(), nullable=False),
    sa.Column('move_id', sa.UUID(), nullable=False),
    sa.Column('learn_method', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['move_id'], ['move.id'], name=op.f('fk_pokemon_move_move_id_move')),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], name=op.f('fk_pokemon_move_pokemon_id_pokemon')),
    sa.PrimaryKeyConstraint('pokemon_id', 'move_id', name=op.f('pk_pokemon_move'))
    )
    op.create_table('pokemon_stats',
    sa.Column('id', GUID(length=16), nullable=False),
    sa.Column('pokemon_id', GUID(length=16), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('special_attack', sa.Integer(), nullable=False),
    sa.Column('special_defense', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], name=op.f('fk_pokemon_stats_pokemon_id_pokemon')),
    sa.PrimaryKeyConstraint('id', 'pokemon_id', name=op.f('pk_pokemon_stats'))
    )
    op.create_table('pokemon_type',
    sa.Column('pokemon_id', sa.UUID(), nullable=False),
    sa.Column('type_id', sa.UUID(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=True),
    sa.CheckConstraint('slot IN (1, 2)', name=op.f('ck_pokemon_type_check_slot_valid')),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], name=op.f('fk_pokemon_type_pokemon_id_pokemon')),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], name=op.f('fk_pokemon_type_type_id_type')),
    sa.PrimaryKeyConstraint('pokemon_id', 'type_id', name=op.f('pk_pokemon_type'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemon_type')
    op.drop_table('pokemon_stats')
    op.drop_table('pokemon_move')
    op.drop_table('type')
    op.drop_table('pokemon')
    op.drop_table('move')
    # ### end Alembic commands ###
