"""Initial schema

Revision ID: 75c8485d26bb
Revises: 
Create Date: 2025-12-09 17:40:56.539940

"""
from typing import Sequence, Union

from alembic import op
from advanced_alchemy.types.guid import GUID
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75c8485d26bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemon',
    sa.Column('id', GUID(length=16), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('sprite_url', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('genus', sa.String(), nullable=False),
    sa.Column('type_display', sa.String(), nullable=False),
    sa.Column('is_legendary', sa.Boolean(), nullable=False),
    sa.Column('is_mythical', sa.Boolean(), nullable=False),
    sa.Column('is_ultra_beast', sa.Boolean(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pokemon')),
    sa.UniqueConstraint('display_name', name=op.f('uq_pokemon_display_name')),
    sa.UniqueConstraint('name', name=op.f('uq_pokemon_name'))
    )
    op.create_table('stat_spread',
    sa.Column('id', GUID(length=16), nullable=False),
    sa.Column('stat_name', sa.String(), nullable=False),
    sa.Column('percentile_20', sa.Integer(), nullable=False),
    sa.Column('percentile_40', sa.Integer(), nullable=False),
    sa.Column('percentile_60', sa.Integer(), nullable=False),
    sa.Column('percentile_80', sa.Integer(), nullable=False),
    sa.Column('percentile_100', sa.Integer(), nullable=False),
    sa.Column('median', sa.Integer(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', 'stat_name', name=op.f('pk_stat_spread'))
    )
    op.create_table('tm',
    sa.Column('id', GUID(length=16), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('machine_id', sa.String(), nullable=True),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tm')),
    sa.UniqueConstraint('machine_id', name=op.f('uq_tm_machine_id')),
    sa.UniqueConstraint('name', name=op.f('uq_tm_name'))
    )
    op.create_table('type',
    sa.Column('id', GUID(length=16), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_type')),
    sa.UniqueConstraint('name', name=op.f('uq_type_name'))
    )
    op.create_table('pokemon_move',
    sa.Column('pokemon_id', sa.UUID(), nullable=False),
    sa.Column('move_name', sa.String(), nullable=False),
    sa.Column('learn_method', sa.String(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], name=op.f('fk_pokemon_move_pokemon_id_pokemon')),
    sa.PrimaryKeyConstraint('pokemon_id', 'move_name', 'learn_method', 'level', name=op.f('pk_pokemon_move'))
    )
    op.create_index('idx_pokemon_moves_by_move', 'pokemon_move', ['move_name'], unique=False)
    op.create_index('idx_pokemon_moves_by_pokemon', 'pokemon_move', ['pokemon_id'], unique=False)
    op.create_table('pokemon_stats',
    sa.Column('id', GUID(length=16), nullable=False),
    sa.Column('pokemon_id', GUID(length=16), nullable=False),
    sa.Column('hp', sa.Integer(), nullable=False),
    sa.Column('attack', sa.Integer(), nullable=False),
    sa.Column('defense', sa.Integer(), nullable=False),
    sa.Column('special_attack', sa.Integer(), nullable=False),
    sa.Column('special_defense', sa.Integer(), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], name=op.f('fk_pokemon_stats_pokemon_id_pokemon')),
    sa.PrimaryKeyConstraint('id', 'pokemon_id', name=op.f('pk_pokemon_stats'))
    )
    op.create_table('pokemon_type',
    sa.Column('pokemon_id', sa.UUID(), nullable=False),
    sa.Column('type_id', sa.UUID(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=True),
    sa.CheckConstraint('slot IN (1, 2)', name=op.f('ck_pokemon_type_check_slot_valid')),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], name=op.f('fk_pokemon_type_pokemon_id_pokemon')),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], name=op.f('fk_pokemon_type_type_id_type')),
    sa.PrimaryKeyConstraint('pokemon_id', 'type_id', name=op.f('pk_pokemon_type'))
    )
    op.create_index('idx_get_pokemon_by_type', 'pokemon_type', ['type_id'], unique=False)
    op.create_table('type_matchup',
    sa.Column('defender_type_id', sa.UUID(), nullable=False),
    sa.Column('attacker_type_id', sa.UUID(), nullable=False),
    sa.Column('multiplier', sa.Float(), nullable=True),
    sa.CheckConstraint('multiplier IN (0, 0.5, 1, 2, 4)', name=op.f('ck_type_matchup_check_multiplier_valid')),
    sa.ForeignKeyConstraint(['attacker_type_id'], ['type.id'], name=op.f('fk_type_matchup_attacker_type_id_type')),
    sa.ForeignKeyConstraint(['defender_type_id'], ['type.id'], name=op.f('fk_type_matchup_defender_type_id_type')),
    sa.PrimaryKeyConstraint('defender_type_id', 'attacker_type_id', name=op.f('pk_type_matchup'))
    )
    op.create_index('idx_get_type_matchups_by_defender', 'type_matchup', ['defender_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_get_type_matchups_by_defender', table_name='type_matchup')
    op.drop_table('type_matchup')
    op.drop_index('idx_get_pokemon_by_type', table_name='pokemon_type')
    op.drop_table('pokemon_type')
    op.drop_table('pokemon_stats')
    op.drop_index('idx_pokemon_moves_by_pokemon', table_name='pokemon_move')
    op.drop_index('idx_pokemon_moves_by_move', table_name='pokemon_move')
    op.drop_table('pokemon_move')
    op.drop_table('type')
    op.drop_table('tm')
    op.drop_table('stat_spread')
    op.drop_table('pokemon')
    # ### end Alembic commands ###
